FORMAT: 1A
HOST: http://localhost:8009

# Employees CRUD API
**This API allows you to inserting, deleting, modifying and searching an employees from a data.json file.**

## Show all Employees [GET /]
**Display all Users/Employees**
+ Response 200 (application/json)
	+ Attributes
		- Employees (array[Employee])

## Search a Employee [GET /{fname}]
**Search an User/Employee**
+ Parameters
	+ fname: `Sravan` (string) - Name of the Employee to delete

+ Response 200 (application/json)
	+ Attributes
		- msg: `Name found` (string) - status of the request
		- obj (array[Employee])

# Data Structures

## Employee (object)
+ fname: `Aditya` (string) - The first name of the employee
+ lname: `Nerella` (string) - The last name of the employee
+ age: `20` (number) - The age of the employee

# Group USER

## GET Access Token [GET /auth/{fname}]
**Generates Authorization token for the existing User**
+ Parameters
	+ fname: `Sravan` (string) - Name of the Employee

+ Response 200 (application/json)
	+ Attributes
		- success: `true` (boolean) - Created a key or not
		- token: `A big big key` (string) - This is the token used to add, delete and modify users

## Employees [/api/emp]

### Add an Employee [POST]
**This operation allows you to add an employee to the data.json file**

+ Request with body (application/x-www-form-urlencoded)
	+ Headers

			token: tokenvalue
	+ Body

            {
                "fname": "Akhil",
                "lname": "Nerella",
                "age": `22`
            }

+ Response 201 (application/json)
	+ Attributes
		- msg: `Employee added successfully` (string) - Status of the request

+ Response 401 (application/json)
	+ Attributes
		- msg: `Invalid request` (string) - Status of the request


### Delete an Employee [DELETE]
**This operation allows you to delete an employee from the data.json file**

+ Request with body (application/x-www-form-urlencoded)
	+ Headers

			token: tokenvalue
	+ Body

            {
                "fname": "Sravan"
            }

+ Response 202 (application/json)
	+ Attributes
		- msg: `Name Deleted` (string) - Status of the deletion

+ Response 401 (application/json)
	+ Attributes
		- msg: `Invalid request` (string) - Status of the request

### Modify an Employee [PUT]
**This operation allows you to modify an employee details with his existing first name**

+ Request with body (application/x-www-form-urlencoded)
	+ Headers

			token: tokenvalue
	+ Body

            {
                "name": "Sravan",
                "fname": "Akhil",
                "lname": "Nerella",
                "age": `22`
            }

+ Response 202 (application/json)
	+ Attributes
		- msg: `Modified` (string) - Status of the request
		- obj (array[Employee])

+ Response 401 (application/json)
	+ Attributes
		- msg: `Invalid request` (string) - Status of the request